
name: MCP LLM

services:
  mcp-llm:
    build: "."
    command: "npm run dev"
    ports:
        - "666:666"
    volumes:
        - ".:/app"
        - "/app/node_modules"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=666"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Preserve host access to local machine
    dns:
      - "8.8.8.8" # Fix windows issue
#    env_file:
#      - ".env"
